Useful tasks understanding Python
=================================
Frank Hofmann
:subtitle:
:doctype: book
:copyright: Frank Hofmann
:revnumber: 1.1
:lang: en
:date: 24 April 2015
:numbered:

= Data structures =

== Lists and list functions ==

. A python list is defined as follows:
+
----
myList = [11, 5, 16, 8, 3]
----
+
.. The list function `reverse()` reverses the order of the list elements
in place. Add two statements to output the list content in reverse
order, and output the new list.

.. The list function `sort()` sorts the list in place in ascending
order (see <<PythonSortingMiniHowTo>> for further details). Sort the
list, and output the new list.

. Lists can be joined using the `+` operator:
+
----
numbers1 = [5, 16, 1, 89, -2]
numbers2 = [45, 66, 1, 3, 89]
names = ["John", "Kate", "Matt", "Bill", "Amy"]
----
+
.. Merge the two lists `numbers1` and `numbers2`, and output the
resulting list.

.. Transform both lists `numbers1` and `numbers2` into a set using the
`set()` function, and calculate the intersection of both sets using the
`intersection()` function.

. `sys` is the name of a python standard module to access various data
from the underlying operating system (see <<sys>> for a full list of
functions). The pre-defined list `sys.argv[]` represents the command
line arguments a python script was called with:
+
----
import sys

fullCall = sys.argv
scriptName = fullCall[0]
parameter1 = fullCall[1]
parameter2 = fullCall[2]
----
+
.. Count the number of parameters the script was called with.

.. Use the `in` operator to check if `--help` is one of the parameters.

== Working with dictionaries ==

. A dictionary belongs to highly structured data. Based on the British
comedy series Little Britain (see <<LittleBritain>>) it can be defined
as follows:
+
----
character1 = {"name": "Kenny Craig", "role": "hypnotist", "playedBy": "Matt Lucas"}
character2 = {"name": "Linda Flint", "role": "teacher", "playedBy": "David Walliams"}
character3 = {"name": "Daffyd Thomas", "role": "journalist", "playedBy": "Matt Lucas"}
characters = [character1, character2, character3]
sketchShow = {
		"series":"Little Britain", 
		"cast": characters,
		"website":"http://www.bbc.co.uk/comedy/littlebritain/"
}
----
+
To retrieve both the name of the sketch show, and its website you write:
+
----
print "name of the series:", sketchShow["series"]
print "series' website:", sketchShow["website"]
----
+
.. Output the roles of the single characters using a `for` loop.
.. Output the names of the single characters that are played by Matt Lucas.

= Graphs and Data Visualization =

== Understanding and Improving the Code ==

. Have a look at this file, first: 
+
https://github.com/hofmannedv/training-python/blob/master/graphs/bars.py
+
.. You would like to add further data to be displayed in the graph. Which lines of the code will have to be changed, then?

.. In line 19, there is a fixed value which represents the number of
bars. Which python function can you use to have always as many bars as
entries, without changing the code next time you either add, or delete
data?

== Reading CSV Data ==

. Have a look at this piece of python code, first:
+
----
import csv

fileHandle = open("data.csv")

for line in csv.reader(fileHandle):
    print(line)
----
+
We assume that the file `data.csv` has the following content:
+
----
City, Region, Country
Strasbourg, Alsace, France
Potsdam, Brandenburg, Germany
Brighton, East Sussex, United Kingdom
----
+
.. How many lines are printed?

.. The string function `split()` can be used to separate a string into
single pieces according to a given separator, for example `", "`. How
does a `split()` function call would look like to receive single columns?

.. Which python function can you use to count the number of columns?

. Have a look at this piece of python code, first:
+
----
import csv

fileHandle = open("data.csv")
fileContent = csv.reader(fileHandle)
----
+
.. The function `csv.reader()` returns a list that contains the content
of the opened file line by line. Which python function can you use to
figure out the number of lines in that file?

.. Extend the program to print every second line, only.

.. Extend the program to print both the before-last, and the last line, only.

= Further Documents =

- [[[LittleBritain]]] Little Britain, official website, http://www.bbc.co.uk/comedy/littlebritain/

- [[[PythonSortingMiniHowTo]]] Python Sorting Mini-How to, https://wiki.python.org/moin/HowTo/Sorting/

- [[[sys]]] sys -- System-specific parameters and functions (documentation), https://docs.python.org/2/library/sys.html#module-sys
